server:
  port: 8080
spring:
  application:
    name: ms-users-api
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    #http://localhost:8080/h2-console
    console:
      enabled: true
      path: /h2-console
swagger:
  #http://localhost:8080/swagger-ui/index.html
  title: "MS-USERS-API"
  description: "Microservice to manage users and phone numbers. Hexagonal architecture."
  version: 1.0.0
jwt:
  secret-key: fShiX4GqlbisgLaOVg+iBKJh6HeKmYyy/DchoUdpLks=
  expiration-time: 3600000 # 1h in millisecond
app:
  password:
   #Esta expresión valida que la password tenga 7 o más caracteres (.{7,}) y contenga al menos un dígito ((?=.*\d)).
   regex: ^(?=.*\d).{7,}$
